function(find_opencv)
    
FetchContent_Declare(opencv GIT_REPOSITORY https://${GIT_HOST}/opencv/opencv.git GIT_TAG 4.8.0 GIT_SHALLOW 1)
set(BUILD_SHARED_LIBS ON)
set(OPENCV_CONFIG_FILE_INCLUDE_DIR ${CMAKE_BINARY_DIR}/opencv_gen_include)
# disable modules
set(BUILD_opencv_apps OFF)
set(BUILD_opencv_aruco OFF)
set(BUILD_opencv_bgsegm OFF)
set(BUILD_opencv_bioinspired OFF)
set(BUILD_opencv_calib3d OFF)
set(BUILD_opencv_ccalib OFF)
set(BUILD_opencv_core ON)
set(BUILD_opencv_datasets OFF)
set(BUILD_opencv_dnn OFF)
set(BUILD_opencv_dnn_objdetect OFF)
set(BUILD_opencv_dnn_superres OFF)
set(BUILD_opencv_dpm OFF)
set(BUILD_opencv_face OFF)
set(BUILD_opencv_flann OFF)
set(BUILD_opencv_features2d OFF)
set(BUILD_opencv_fuzzy OFF)
set(BUILD_opencv_gapi OFF)
set(BUILD_opencv_hfs OFF)
set(BUILD_opencv_highgui OFF)
set(BUILD_opencv_imgcodecs ON)
set(BUILD_opencv_imgproc ON)
set(BUILD_opencv_intensity_transform OFF)
set(BUILD_opencv_line_descriptor OFF)
set(BUILD_opencv_mcc OFF)
set(BUILD_opencv_ml OFF)
set(BUILD_opencv_objdetect OFF)
set(BUILD_opencv_optflow OFF)
set(BUILD_opencv_phase_unwrapping OFF)
set(BUILD_opencv_photo OFF)
set(BUILD_opencv_plot OFF)
set(BUILD_opencv_quality OFF)
set(BUILD_opencv_rapid OFF)
set(BUILD_opencv_reg OFF)
set(BUILD_opencv_rgbd OFF)
set(BUILD_opencv_saliency OFF)
set(BUILD_opencv_shape OFF)
set(BUILD_opencv_stereo OFF)
set(BUILD_opencv_stitching OFF)
set(BUILD_opencv_structured_light OFF)
set(BUILD_opencv_superres OFF)
set(BUILD_opencv_surface_matching OFF)
set(BUILD_opencv_text OFF)
set(BUILD_opencv_tracking OFF)
set(BUILD_opencv_ts OFF)
set(BUILD_opencv_video OFF)
set(BUILD_opencv_videoio OFF)
set(BUILD_opencv_videostab OFF)
set(BUILD_opencv_world ON)
set(BUILD_opencv_wechat_qrcode OFF)
set(BUILD_opencv_xfeatures2d OFF)
set(BUILD_opencv_ximgproc OFF)
set(BUILD_opencv_xobjdetect OFF)
set(BUILD_opencv_xphoto OFF)
# disable python
set(BUILD_opencv_python_bindings_generator OFF)
set(BUILD_opencv_python_tests OFF)
# disable java
set(BUILD_JAVA OFF)
set(BUILD_opencv_java_bindings_generator OFF)
# disable js
set(BUILD_opencv_js OFF)
set(BUILD_opencv_js_bindings_generator OFF)
# disable objc
set(BUILD_opencv_objc_bindings_generator OFF)
# not test
set(BUILD_TESTS OFF)
set(BUILD_PERF_TESTS OFF)
set(BUILD_EXAMPLES OFF)
set(BUILD_DOCS OFF)
set(BUILD_WITH_DEBUG_INFO OFF)
# no itt
set(WITH_ITT OFF)
set(BUILD_ITT OFF)
set(ccitt OFF)
# pic
set(BUILD_SHARED_LIBS OFF)
set(BUILD_WITH_STATIC_CRT ON)
# 启用位置无关代码
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
FetchContent_MakeAvailable(opencv)

endfunction()
